tap "UpCloudLtd/tap"



brew "awscli"
brew "docker"
brew "ddev/ddev/ddev"
brew "cocoapods"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "mas"
brew "spaceship"
brew "yt-dlp"
brew "stripe/stripe-cli/stripe"
brew "zoxide"


brew "kubectx"
brew "stern"
brew "bat"
brew "k9s"
brew "skaffold"
brew "kubectl"
brew "mkcert"
brew "kubeseal"
cask "1password-cli"
brew "argocd"
brew "cloudflared"
brew "upcloud-cli"
brew "pwgen"
brew "git-flow"
brew "kustomize"
brew "helm"
brew "hashicorp/tap/terraform"
brew "nvm"
brew "tree"
brew "withgraphite/tap/graphite"
brew "nss"

cask  "orbstack"
cask	"cursor"
cask "1password"
cask "1password-cli"
cask "bartender"
cask "brave-browser"
cask "chatgpt"
cask "cleanshot"
cask "dropshare"
cask "discord"
cask "figma"
cask "firefox"
cask "flux-app"
cask "hammerspoon"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "keymapp"
cask "linear-linear"
cask "logi-options+"
cask "nova"
cask "phpstorm"
cask "postman"
cask "protonvpn"
cask "slack"
cask "spotify"
cask "tableplus"
cask "tower"
cask "transmit"
cask "tidal"
cask "zoom"

mas "Things", id: 904280696
mas "Pages", id: 409201541
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
