tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "awscli"
brew "cocoapods"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "mas"
brew "yt-dlp"
brew "stripe/stripe-cli/stripe"

cask "1password"
cask "bartender"
cask "chatgpt"
cask "cleanshot"
cask "dropshare"
cask "discord"
cask "figma"
cask "firefox"
cask "flux"
cask "github"
cask "google-chrome"
cask "hammerspoon"
cask "herd"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "keymapp"
cask "linear-linear"
cask "nova"
cask "obs"
cask "phpstorm"
cask "ray"
cask "spaceship"
cask "spotify"
cask "tableplus"
cask "tower"
cask "transmit"
cask "zoom"

mas "Things", id: 904280696
mas "Pages", id: 409201541
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
